apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_ERLANG_COOKIE: <BASE64_ENCODED_ERLANG_COOKIE>
  RABBITMQ_DEFAULT_USER: <BASE64_ENCODED_USER>
  RABBITMQ_DEFAULT_PASS: <BASE64_ENCODED_PASS>
